apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
    processors:
      - add_kubernetes_metadata:
          in_cluster: true
  
    output.logstash:
      hosts: ["logstash.logging.svc.cluster.local:5044"]